name: one_day_focus
description: A task management & alarm app focused on "Today only".
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  flutter_local_notifications: ^16.3.3
  audioplayers: ^5.2.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
